# A receita de configuração.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# O identificador único do projeto do assistente
# Este valor padrão deve ser substituído por um nome de assistente único em sua implantação
assistant_id: identificador_unico

# Configuração para Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
    OOV_token: oov
    token_pattern: (?u)\b\w+\b
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-multilingual-cased"
    use_transformers: true
  - name: DIETClassifier
    epochs: 100


policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
